HTTPServer:
  Addr: ':8080'
  MaxHeaderBytes: 1048576
  IdleTimeout: 600s
  ReadHeaderTimeout: 1s
  ReadTimeout: 1s
  WriteTimeout: 7s
  Router:
    MiddlewareTimeout: 6s
HTTPClient:
  Timeout: 4s
  UserAgent: 'feed'
Mongo:
  URI: mongodb://localhost:27017
  AppName: feedado
  Timeout: 2